function OEPKwik_to_dat()
% transmute an OEP .kwik to a raw .dat file
% no input parameters
% subtracts AUX channels (3, hardcoded)
% 
% written by Brian Sadacca 12-9-2015
% last modified by ...

% get the data
[filename filepath]=uigetfile(...
    '*.kwd','raw-kwd kwik format files as generated by OpenEphys');

% load the data
cd(filepath)
xxx=h5read(filename,'/recordings/0/data');

% create/open a raw file
fid=fopen('sampledata.dat','w+');

% write data to raw file
fwrite(fid,xxx(1:end-3,:),'int16');

% close that file
fclose(fid);
disp(['file ',filename,' converted'])
end